Spoi 10646 upgrade demo apps
DataTorrent/Megh pull request #217
Opened 2017-01-30 15:15 UTC by francisf

@tushargosavi Please review
As discussed, following exception was seen
```
Caused by: java.lang.NullPointerException
	at com.datatorrent.netlet.util.Slice.<init>(Slice.java:42)
	at com.datatorrent.contrib.hdht.HDHTReader.<clinit>(HDHTReader.java:250)
	... 11 more
```
Primarily seen due to netlet error (master has fix for null check but not present in tag 1.3.0 which is the latest available in the mvn repository). As discussed have made change in Megh rather than Apex-Core(+netlet version up). 

Since malhar-version was bumped up checkstyle violations for trailing spaces were thrown.

2017-02-05 16:07 UTC, vrozov commented
The fix for NullPointerException is available in netlet 1.3.0 and it is posted to maven central repository.

2017-02-05 16:18 UTC, vrozov requested changes

2017-02-05 16:18 UTC, vrozov commented on contrib/src/main/java/com/datatorrent/contrib/dimensions/AbstractAppDataDimensionStoreHDHT.java
> +
All format/codestyle related changes must be done in a separate commit (or even in a separate PR with separate JIRA) using Malhar Jenkins user.

2017-02-05 16:18 UTC, vrozov commented on contrib/src/main/java/com/datatorrent/contrib/hdht/HDHTReader.java
> +  private static Slice GET_KEY = new Slice(new byte[] {0}, 0, 1);
Not needed

2017-02-05 16:18 UTC, vrozov commented on contrib/src/main/java/com/datatorrent/contrib/hdht/HDHTReader.java
> +        Slice value = new Slice(new byte[] {0}, 0,1);
Not needed

2017-02-05 16:18 UTC, vrozov commented on contrib/src/main/java/com/datatorrent/contrib/hdht/HDHTWriter.java
> +    Slice key = new Slice(new byte[] {0}, 0, 1);
Not needed

2017-02-05 16:18 UTC, vrozov commented on pom.xml
> +    <version>3.6.0</version>
Why is it necessary to upgrade malhar version? Is there any particular issue fixed in malhar 3.6.0 that justifies the upgrade?

2017-02-06 05:39 UTC, francisf commented on contrib/src/main/java/com/datatorrent/contrib/hdht/HDHTWriter.java
> +    Slice key = new Slice(new byte[] {0}, 0, 1);
@vrozov There seems to be a difference in [tag 1.3.0](https://github.com/DataTorrent/Netlet/blob/v1.3.0/src/main/java/com/datatorrent/netlet/util/Slice.java#L42) and [master](https://github.com/DataTorrent/Netlet/blob/master/src/main/java/com/datatorrent/netlet/util/Slice.java#L42) for the null check. @tushargosavi decompiled netlet 1.3.0 from the maven repo and we see that the null check is missing.

2017-02-06 05:44 UTC, francisf commented on contrib/src/main/java/com/datatorrent/contrib/dimensions/AbstractAppDataDimensionStoreHDHT.java
> +
@vrozov I'll separate the commit in another PR. Can you point me to some docs that describe how  to do this as malhar jenkins user?

2017-02-06 06:50 UTC, vrozov commented on contrib/src/main/java/com/datatorrent/contrib/dimensions/AbstractAppDataDimensionStoreHDHT.java
> +
`git commit --author=<jenkins@datatorrent.com>`. Please open another JIRA. Format changes are not directly related to the upgrade.

2017-02-06 07:17 UTC, vrozov commented on contrib/src/main/java/com/datatorrent/contrib/hdht/HDHTWriter.java
> +    Slice key = new Slice(new byte[] {0}, 0, 1);
tag 1.3.0 was not correctly applied in Datatorrent/Netlet. I fixed the tag.

2017-02-08 05:09 UTC, closed without merging